In [9]:
import pandas as pd
import numpy as np

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
file_path = "/content/drive/MyDrive/Colab Notebooks/customer_train.csv"
df_customer = pd.read_csv(file_path)
df_customer.head()

,customer_id,country,gender,membership_tier,preferred_category,preferred_device,preferred_payment_method,acquisition_channel,age,total_orders,...,reviews_given,avg_review_score,returns_made,wishlist_items,newsletter_subscribed,customer_tenure_days,orders_per_year,reviews_per_order,returns_per_order,churned
0,C02470,United States,Female,Free,Books,Desktop,Credit Card,Organic Search,35,1,...,0,4.6,0,7,1,1023,0.357038,0.000000,0.000000,0
1,C01365,South Korea,Male,Free,Home & Kitchen,Desktop,Credit Card,Social Media,30,60,...,8,4.6,4,11,1,215,101.930233,0.133333,0.066667,0
2,C05213,Brazil,Female,Silver,Health & Wellness,Desktop,Credit Card,Social Media,33,13,...,3,4.3,1,1,0,1596,2.975094,0.230769,0.076923,0
3,C02126,India,Female,Free,Home & Kitchen,Mobile,Debit Card,Direct,39,26,...,3,4.0,3,0,0,1993,4.764927,0.115385,0.115385,0
4,C04709,United States,Female,Silver,Toys & Games,Mobile,Debit Card,Organic Search,50,16,...,3,4.7,0,0,0,571,10.234676,0.187500,0.000000,0

In [11]:
file_path = "/content/drive/MyDrive/Colab Notebooks/customer_test.csv"
df_customer_test = pd.read_csv(file_path)
df_customer_test.head()

,customer_id,country,gender,membership_tier,preferred_category,preferred_device,preferred_payment_method,acquisition_channel,age,total_orders,...,reviews_given,avg_review_score,returns_made,wishlist_items,newsletter_subscribed,customer_tenure_days,orders_per_year,reviews_per_order,returns_per_order,churned
0,C07041,India,Female,Gold,Electronics,Desktop,UPI / Digital Wallet,Social Media,32,10,...,0,4.0,0,7,1,152,24.029605,0.000000,0.0,0
1,C01731,South Africa,Male,Silver,Home & Kitchen,Tablet,UPI / Digital Wallet,Social Media,36,15,...,0,4.0,0,2,1,175,31.307143,0.000000,0.0,0
2,C07703,Poland,Female,Free,Jewelry & Accessories,Mobile,PayPal,Social Media,36,10,...,3,5.0,1,4,0,1058,3.452268,0.300000,0.1,0
3,C00712,United States,Female,Free,Automotive,Desktop,Credit Card,Social Media,43,9,...,1,3.3,0,7,1,198,16.602273,0.111111,0.0,0
4,C03891,Netherlands,Female,Free,Automotive,Desktop,Credit Card,Paid Ad,21,5,...,1,3.5,0,4,1,369,4.949187,0.200000,0.0,0

## k-Nearest Neighbor

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [13]:
# Check data size
len(df_customer) #train_data

6400

In [14]:
# 3. Create the Model
model = KNeighborsClassifier(n_neighbors=7) # k = 7

In [15]:
model

KNeighborsClassifier(n_neighbors=7)

In [18]:
X_train = df_customer.drop(['customer_id','churned'], axis=1)
y_train = df_customer['churned']

In [19]:
# Train the model
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'United States'

In [20]:
TARGET = "churned"
ID_COLUMN = "customer_id"

CATEGORICAL_COLUMNS = [
    "country",
    "gender",
    "membership_tier",
    "preferred_category",
    "preferred_device",
    "preferred_payment_method",
    "acquisition_channel",
]

NUMERIC_COLUMNS = [
    "age",
    "total_orders",
    "total_spend_usd",
    "avg_order_value_usd",
    "days_since_last_purchase",
    "reviews_given",
    "avg_review_score",
    "returns_made",
    "wishlist_items",
    "newsletter_subscribed",
    # engineered features
    "customer_tenure_days",
    "orders_per_year",
    "reviews_per_order",
    "returns_per_order",
]

In [21]:
X_train = df_customer[NUMERIC_COLUMNS]
y_train = df_customer[TARGET]

In [22]:
# Train the model
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [23]:
# 4. Test the Model
X_test=df_customer_test[NUMERIC_COLUMNS]
y_test=df_customer_test[TARGET]

In [24]:
y_pred = model.predict(X_test)

In [25]:
result = pd.DataFrame({"y_test":y_test, "y_pred":y_pred})
result.head(10)

   y_test  y_pred
0       0       0
1       0       0
2       0       0
3       0       0
4       0       0
5       0       0
6       0       0
7       1       0
8       0       0
9       1       0

In [26]:
# 5. Evaluation Metrics
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average="macro"))
print("Recall:", recall_score(y_test, y_pred, average="macro"))
print("F1 Score:", f1_score(y_test, y_pred, average="macro"))

Accuracy: 0.910625
Precision: 0.7076485461441213
Recall: 0.5283799933765617
F1 Score: 0.5323731449745442